### PR TITLE
fix(gcpnfsvolumerestore): preventing duplicate filestore restores

### LINKED ISSUE #584: Sometimes GcpNfsVolumeRestore get applied twice
**Description**

Sometimes, the restore happens twice which puts the filestore in an unusable state twice the actual time it needs to be. This can be few extra minutes of unnecessary operation and cost.

**Expected result**

**Actual result**

**Steps to reproduce**

**Troubleshooting**

### PR DESCRIPTION
**Pull request by abalaie**
**Description**

Changes proposed in this pull request:

- Introducing leasing mechanism to prevent conflicting actions
- Adding api to restore client to find an existing running restore to prevent duplicate execution of restore 

**Related issue(s)**

Resolves #584

### CODE REVIEW

File: pkg/skr/common/leases/lease.go [hunk 1]
```diff
@@ -0,0 +1,110 @@
...
+				RenewTime:            &metav1.MicroTime{Time: time.Now()},
+			},
+		}
+		err := cluster.K8sClient().Create(ctx, lease)
+		if err != nil {
+			return LeasingFailed, err
+		}
+		return AcquiredLease, nil
+	}
+	if *lease.Spec.HolderIdentity == holderName {
```
Comment (dushanpantic) [inline pkg/skr/common/leases/lease.go:62]:
```suggestion
	if ptr.Deref(lease.Spec.HolderIdentity, "") == holderName {
```
As `HolderIdentity` is optional in `LeaseSpec`, I think we should be safe here and avoid potential nil pointer

File: pkg/skr/common/leases/lease.go [hunk 2]
```diff
@@ -0,0 +1,110 @@
...
+		lease.Spec.RenewTime = &metav1.MicroTime{Time: time.Now()}
+		err := cluster.K8sClient().Update(ctx, lease)
+		if err != nil {
+			return LeasingFailed, err
+		}
+		return RenewedLease, nil
+	} else {
+		if lease.Spec.RenewTime == nil || lease.Spec.RenewTime.Time.Add(time.Second*time.Duration(*lease.Spec.LeaseDurationSeconds)).Before(time.Now()) {
```
Comment (dushanpantic) [inline pkg/skr/common/leases/lease.go:70]:
```suggestion
                leaseDurationSeconds = ptr.Deref(lease.Spec.LeaseDurationSeconds, leaseDuration)
		if lease.Spec.RenewTime == nil || lease.Spec.RenewTime.Time.Add(time.Second*time.Duration(leaseDurationSeconds)).Before(time.Now()) {
```
As `LeaseDurationSeconds` is optional in `LeaseSpec`, I think we should be safe here and avoid potential nil pointer

File: pkg/skr/common/leases/lease.go [hunk 3]
```diff
@@ -0,0 +1,110 @@
...
+	defer leaseMutex.Unlock()
+	leaseName := getLeaseName(resourceName, prefix)
+	leaseNamespace := resourceName.Namespace
+	holderName := getHolderName(ownerName)
+	lease := &v1.Lease{}
+	err := cluster.K8sClient().Get(ctx, types.NamespacedName{Name: leaseName, Namespace: leaseNamespace}, lease)
+	if err != nil && !apierrors.IsNotFound(err) {
+		return err
+	}
+	if lease.Name != "" && *lease.Spec.HolderIdentity == holderName {
```
Comment (dushanpantic) [inline pkg/skr/common/leases/lease.go:95]:
```suggestion
	if lease.Name != "" && ptr.Deref(lease.Spec.HolderIdentity, "") == holderName {
```

File: pkg/skr/gcpnfsvolumerestore/findRestoreOperation.go [hunk 4]
```diff
@@ -0,0 +1,66 @@
...
+
+	//If deleting, continue with next steps.
+	if composed.MarkedForDeletionPredicate(ctx, st) {
+		return nil, nil
+	}
+
+	restore := state.ObjAsGcpNfsVolumeRestore()
+	opName := restore.Status.OpIdentifier
+	logger.WithValues("Nfs Restore source:", restore.Spec.Source.Backup.ToNamespacedName(state.Obj().GetNamespace()),
+		"destination:", restore.Spec.Destination.Volume.ToNamespacedName(state.Obj().GetNamespace())).Info("Finding GCP Restore Operations")
```
Comment (dushanpantic) [inline pkg/skr/gcpnfsvolumerestore/findRestoreOperation.go:27]:
```suggestion
	logger.WithValues("nfsRestoreSource", restore.Spec.Source.Backup.ToNamespacedName(state.Obj().GetNamespace()),
		"destination", restore.Spec.Destination.Volume.ToNamespacedName(state.Obj().GetNamespace())).Info("Finding GCP Restore Operations")
```
`:` will be added automatically, and our log aggregator (gcp logging) prefers if we use single words for keys.

File: pkg/skr/gcpnfsvolumerestore/findRestoreOperation.go [hunk 5]
```diff
@@ -0,0 +1,66 @@
...
+	dstLocation := state.GcpNfsVolume.Status.Location
+	nfsInstanceName := fmt.Sprintf("cm-%.60s", state.GcpNfsVolume.Status.Id)
+	op, err := state.fileRestoreClient.FindRestoreOperation(ctx, project, dstLocation, nfsInstanceName)
+	if err != nil {
+		var e *googleapi.Error
+		if ok := errors.As(err, &e); ok {
+			if e.Code == 404 {
+				return nil, nil
+			}
+		}
```
Comment (dushanpantic) [inline pkg/skr/gcpnfsvolumerestore/findRestoreOperation.go:44]: Please consider using this method: https://github.com/kyma-project/cloud-manager/blob/de90d6cfd2d3a107728b131769375414245d2d47/pkg/kcp/provider/gcp/meta/metadata.go#L9

**Review by dushanpantic — CHANGES_REQUESTED** [review]
I am requesting changes because of the unsafe pointer dereferences.
In a case where `Lease`.`Spec` gets malformed by either some bug or user, our cloud-manager would crash on `nil` pointer dereference.

In the review, there are also some style change suggestions. Feel free to disregard them if you don't agree with them.

File: pkg/skr/common/leases/lease.go [hunk 6]
```diff
@@ -0,0 +1,110 @@
...
+	holderName := getHolderName(ownerName)
+
+	lease := &v1.Lease{}
+	err := cluster.K8sClient().Get(ctx, types.NamespacedName{Name: leaseName, Namespace: leaseNamespace}, lease)
+	if err != nil && !apierrors.IsNotFound(err) {
+		return LeasingFailed, err
+	}
+	leaseDuration := new(int32)
+
+	*leaseDuration = int32(config.SkrRuntimeConfig.SkrLockingLeaseDuration.Seconds())
```
[the remark this answers is not in the document]
Comment (abalaie) [reply pkg/skr/common/leases/lease.go]: Done

File: pkg/skr/common/leases/lease.go [hunk 7]
```diff
@@ -0,0 +1,110 @@
...
+			lease.Spec.RenewTime = &metav1.MicroTime{Time: time.Now()}
+			lease.Spec.HolderIdentity = &holderName
+			err := cluster.K8sClient().Update(ctx, lease)
+			if err != nil {
+				return LeasingFailed, err
+			}
+			return AcquiredLease, nil
+		}
+		return OtherLeased, nil
+	}
```
[the remark this answers is not in the document]
Comment (abalaie) [reply pkg/skr/common/leases/lease.go]: done

File: pkg/skr/common/leases/lease.go (hunk 3 above)
Comment (abalaie) [reply pkg/skr/common/leases/lease.go]: done

File: pkg/skr/gcpnfsvolumerestore/findRestoreOperation.go (hunk 4 above)
Comment (abalaie) [reply pkg/skr/gcpnfsvolumerestore/findRestoreOperation.go]: done. I did the same in other actions as well.

File: pkg/skr/common/leases/lease.go (hunk 1 above)
Comment (abalaie) [reply pkg/skr/common/leases/lease.go]: Done

File: pkg/skr/common/leases/lease.go (hunk 2 above)
Comment (abalaie) [reply pkg/skr/common/leases/lease.go]: Done.

File: pkg/skr/gcpnfsvolumerestore/findRestoreOperation.go (hunk 5 above)
Comment (abalaie) [reply pkg/skr/gcpnfsvolumerestore/findRestoreOperation.go]: Done.

File: pkg/skr/gcpnfsvolumerestore/checkRestoreOperation.go [hunk 8]
```diff
@@ -19,7 +19,7 @@ func checkRestoreOperation(ctx context.Context, st composed.State) (error, conte
 
 	restore := state.ObjAsGcpNfsVolumeRestore()
 	opName := restore.Status.OpIdentifier
-	logger.WithValues("Nfs Restore source:", restore.Spec.Source.Backup.ToNamespacedName(state.Obj().GetNamespace()),
+	logger.WithValues("nfsRestoreSource:", restore.Spec.Source.Backup.ToNamespacedName(state.Obj().GetNamespace()),
```
Comment (dushanpantic) [inline pkg/skr/gcpnfsvolumerestore/checkRestoreOperation.go:22]:
```suggestion
	logger.WithValues("nfsRestoreSource", restore.Spec.Source.Backup.ToNamespacedName(state.Obj().GetNamespace()),
```
Please remove the `:` at the end, as it is added automatically in the log aggregator.
`logger.Withvalues("foo", "bar")` will display `foo: bar`
`logger.WithValues("foo:", "bar")` will display `foo:: bar`

File: pkg/skr/gcpnfsvolumerestore/findRestoreOperation.go [hunk 9]
```diff
@@ -0,0 +1,62 @@
...
+
+	//If deleting, continue with next steps.
+	if composed.MarkedForDeletionPredicate(ctx, st) {
+		return nil, nil
+	}
+
+	restore := state.ObjAsGcpNfsVolumeRestore()
+	opName := restore.Status.OpIdentifier
+	logger.WithValues("nfsRestoreSource:", restore.Spec.Source.Backup.ToNamespacedName(state.Obj().GetNamespace()),
+		"destination:", restore.Spec.Destination.Volume.ToNamespacedName(state.Obj().GetNamespace())).Info("Finding GCP Restore Operations")
```
Comment (dushanpantic) [inline pkg/skr/gcpnfsvolumerestore/findRestoreOperation.go:26]:
```suggestion
	logger.WithValues("nfsRestoreSource", restore.Spec.Source.Backup.ToNamespacedName(state.Obj().GetNamespace()),
		"destination", restore.Spec.Destination.Volume.ToNamespacedName(state.Obj().GetNamespace())).Info("Finding GCP Restore Operations")
```

**Review by dushanpantic — COMMENTED** [review]
The flow seems good to me, I have dismissed the previous review.

Please implement the asked logging changes as they relate to https://github.com/kyma-project/cloud-manager/issues/383

**Review by dushanpantic — APPROVED** [review]
Approving so it doesnt block. Please take a look at the previous comment
