### PR TITLE
fix(BackupSchedule): flaky test

### LINKED ISSUE #988: Backup schedule - flaky test
**Description**
Backup schedule - evaluateNextRun.TestWhenNextRunTimeIsNotDueYet() fails occasionally.

This happens when the test runs across the seconds boundary.

**Expected result**
Test should be always successful

**Actual result**

**Steps to reproduce**

**Troubleshooting**

### PR DESCRIPTION
**Pull request by ravi-shankar-sap**
**Description**

Changes proposed in this pull request:

- Fix for occasional failure of test evaluateNextRun.TestWhenNextRunTimeIsNotDueYet()

**Related issue(s)**

Fixes #988

### CODE REVIEW

File: pkg/skr/backupschedule/evaluateNextRun_test.go [hunk 1]
```diff
@@ -126,7 +126,12 @@ func (suite *evaluateNextRunSuite) TestWhenNextRunTimeIsNotDueYet() {
 	err, _ = evaluateNextRun(ctx, state)
 
 	//validate expected return values
-	suite.Equal(composed.StopWithRequeueDelay(offset), err)
+	result, err := composed.HandleWithoutLogging(err, ctx)
+	delay := result.RequeueAfter
+	suite.Nil(err)
+	suite.NotNil(delay)
+	suite.Greater(delay, time.Duration(0))
```
Comment (tmilos77) [inline pkg/skr/backupschedule/evaluateNextRun_test.go:133]: Why allow so big gap? Give it some relative tolerance, like 5%. 
```suggestion
	suite.Greater(delay, time.Duration(int64(0.95 * float64(offset))))
```

**Review by tmilos77 — CHANGES_REQUESTED** [review]

**Review by kevin-kho — APPROVED** [review]
lgtm

**Review by tmilos77 — APPROVED** [review]
